apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ncractiveclusters.ncr.netease.com
spec:
  group: ncr.netease.com
  names:
    kind: NcrActiveCluster
    listKind: NcrActiveClusterList
    plural: ncractiveclusters
    singular: ncractivecluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the behavior of a ncr cluster
            properties:
              act:
                type: string
              activeNodePhase:
                type: string
              autoRecover:
                type: boolean
              logicMaster:
                type: boolean
              mode:
                type: string
              name:
                type: string
              preCluster:
                properties:
                  clusterName:
                    type: string
                  k8SClusterId:
                    type: string
                  k8SClusterName:
                    type: string
                  namespace:
                    type: string
                  nodes:
                    items:
                      properties:
                        ipAddr:
                          type: string
                      type: object
                    type: array
                  password:
                    type: string
                  sentinelMasterName:
                    type: string
                  sentinelPassword:
                    type: string
                type: object
              recoverStrategy:
                properties:
                  failover:
                    type: boolean
                  sharedDown:
                    type: boolean
                type: object
            type: object
        required:
        - metadata
        - spec
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
