apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ncractiveclusters.ncr.netease.com
spec:
  group: ncr.netease.com
  names:
    kind: NcrActiveCluster
    listKind: NcrActiveClusterList
    plural: ncractiveclusters
    singular: ncractivecluster
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              act:
                type: string
              activeNodePhase:
                type: string
              autoRecover:
                type: boolean
              logicMaster:
                type: boolean
              mode:
                type: string
              name:
                type: string
            type: object
        type: object
    served: true
    storage: true
